# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Adcroft
title-normal: Generator of Ocean Code
email: youremailaddress@gmail.com
description: Senior Research Oceanographer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adcroft.github.io" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
  - jekyll/scholar

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: https://www.facebook.com/alistair.adcroft
github_url: https://github.com/adcroft 
gitlab_url:
googleplus_url: https://plus.google.com/u/0/+AlistairAdcroft
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/AlistairAdcroft

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: alistairadcroft
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 

# Plugin: jekyll/scholar
scholar:
  style: american-meteorological-society
  locale: en

  sort_by: year
  order: descending

  group_by: year
  group_order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bibitem

  replace_strings: true
  join_strings:    true

  bibtex_filters:
  - superscript
  - latex

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
